"""empty message

<<<<<<<< HEAD:migrations/versions/876a9e79a789_.py
Revision ID: 876a9e79a789
Revises: 
Create Date: 2022-12-11 19:08:33.115711
========
Revision ID: 5f2e3eda0081
Revises: 
Create Date: 2022-12-12 22:24:41.361956
>>>>>>>> origin/feature/users:migrations/versions/5f2e3eda0081_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/876a9e79a789_.py
revision = '876a9e79a789'
========
revision = '5f2e3eda0081'
>>>>>>>> origin/feature/users:migrations/versions/5f2e3eda0081_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('models')
    # ### end Alembic commands ###
